// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYbNoUHNe2pqCIzDNlzyg1eazBEoIoKjk',
    appId: '1:586672149984:web:3f5d8c993905b8424e4785',
    messagingSenderId: '586672149984',
    projectId: 'shamba-langu-apk',
    authDomain: 'shamba-langu-apk.firebaseapp.com',
    storageBucket: 'shamba-langu-apk.appspot.com',
    measurementId: 'G-R4ZJHFKS2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB47a0P9Go3Ar99gn3tVHbs_S2paTQ8U0',
    appId: '1:586672149984:android:65453282d1423d874e4785',
    messagingSenderId: '586672149984',
    projectId: 'shamba-langu-apk',
    storageBucket: 'shamba-langu-apk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWvohtAqqOsocybUmIoUqKnBxwYxDhYNg',
    appId: '1:586672149984:ios:56ca76ef7b157df84e4785',
    messagingSenderId: '586672149984',
    projectId: 'shamba-langu-apk',
    storageBucket: 'shamba-langu-apk.appspot.com',
    iosClientId: '586672149984-l3ingai7dpu30ekrdaakr70jmqffsaf5.apps.googleusercontent.com',
    iosBundleId: 'com.example.shamba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWvohtAqqOsocybUmIoUqKnBxwYxDhYNg',
    appId: '1:586672149984:ios:56ca76ef7b157df84e4785',
    messagingSenderId: '586672149984',
    projectId: 'shamba-langu-apk',
    storageBucket: 'shamba-langu-apk.appspot.com',
    iosClientId: '586672149984-l3ingai7dpu30ekrdaakr70jmqffsaf5.apps.googleusercontent.com',
    iosBundleId: 'com.example.shamba',
  );
}
